
services:
  web:
    container_name: chhanvirakbuth-me
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - web

networks:
  web:
    external: true
